name: Test on Branch

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  issues: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Build
        uses: ./.github/actions/build
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
